server:
  http_listen_port: 28183
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://[fd0d:a262:1fa6:e621:b4e1:08ff:e658:6f49]:3100/loki/api/v1/push
    external_labels:
      host: nixos-8gb-fsn1-1
  - url: http://[fd0d:a262:1fa6:e621:47e6:24d4:2acb:9437]:3100/loki/api/v1/push
    external_labels:
      host: nutty-noon

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
