# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon";
    rev = "e8b8ac8908c6623f0fd7ffccc7de3882a773b72f";
    sha256 = "09b783zmk8hmliyf52jf2ffyq1lyx8p39dyp80ybpd1affq09smk";
  };
in applyPatches {
  inherit src;
  patches = [];
}
