# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon";
    rev = "c1d0a6a7981b5fe74bdd03c958a558096ea3cde8";
    sha256 = "1ybhj352wb704b2fa7vnnfzn421m03vnv5w2fy3jfikn51765bhl";
  };
in applyPatches {
  inherit src;
  patches = [];
}
