# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon";
    rev = "252deefe3433d0cedafd973becd0d85b5182eb49";
    sha256 = "0ld2nadl48blwcabgrp9wjx3ha750s9dvvrdf0l5dv9qy6nipw4l";
  };
in applyPatches {
  inherit src;
  patches = [];
}
