keys:
  - &lotte 46C6A7E14BC7812E86C2700737FE303AAC2D06CD
  - &nixos-8gb-fsn1-1 age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
  - &nutty-noon age1wfftrnyngg7nxcwvt7m590fwx3w7p4kkrjn9uprjq0u3k3ym4s3qqzkmzm
  - &thinkrac age15c2dquc22epmmndpmd8pa3077fdl8nyr5qehr7y0c9uvavrledsq326ak9
  - &nas age1c7y687sxh428wk34s8ws6kemu62mggafpt40rmanevgkuj5xa59q6f7tlc
  - &instance-20221213-1915 age1s7xxqxk6t6rw3zvfylgpwp5362v5guqsf8vjcvjjdj7wcnnxncvqc62frn
creation_rules:
  - path_regex: secrets/nixos-8gb-fsn1-1\.yaml$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
        pgp:
          - *lotte
  - path_regex: secrets/nutty-noon\.yaml$
    key_groups:
      - age:
          - *nutty-noon
        pgp:
          - *lotte
  - path_regex: secrets/thinkrac\.yaml$
    key_groups:
      - age:
          - *thinkrac
        pgp:
          - *lotte
  - path_regex: secrets/nixos\.yaml$
    key_groups:
      - pgp:
          - *lotte
  - path_regex: secrets/nas\.yaml$
    key_groups:
      - age:
          - *nas
        pgp:
          - *lotte
  - path_regex: secrets/desktop\.yaml$
    key_groups:
      - age:
          - *nutty-noon
          - *thinkrac
        pgp:
          - *lotte
  - path_regex: secrets/instance-20221213-1915\.yaml$
    key_groups:
      - age:
          - *instance-20221213-1915
        pgp:
          - *lotte
