keys:
  - &lotte 46C6A7E14BC7812E86C2700737FE303AAC2D06CD
  - &nixos-8gb-fsn1-1 age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
  - &nutty-noon age1zgxkntdp99dkvw7z29jjmgrzlla2ha542zrs3262dwat27a34asqckfkrl
  - &thinkrac age1e7tqq7ezjtwsunt6plvstevg32p97cmqpejpj20gmrkfe0l7gv9se08zf7
creation_rules:
  - path_regex: secrets/nixos-8gb-fsn1-1\.yaml$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
        pgp:
          - *lotte
  - path_regex: secrets/nutty-noon\.yaml$
    key_groups:
      - age:
          - *nutty-noon
        pgp:
          - *lotte
  - path_regex: secrets/thinkrac\.yaml$
    key_groups:
      - age:
          - *thinkrac
        pgp:
          - *lotte
  - path_regex: secrets/nixos\.yaml$
    key_groups:
      - pgp:
          - *lotte
