keys:
  - &base age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
  - &darkkirb age15g6tzvcmcp3ae4hwnn4pwewat6eq9unlhtjrlaka6rf94ej9dd5qqpgt7u
  - &instance-20221213-1915 age1elra3uklw8rmwkevqms2l4tsd06d5utqda9d2w4qvqpz898uzuesugxkhc
  - &nas age1c7y687sxh428wk34s8ws6kemu62mggafpt40rmanevgkuj5xa59q6f7tlc
  - &nixos-8gb-fsn1-1 age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
  - &not522 age1nvgqlpqe026czej7erz5a7ptulzzhh7tht3gjzy5s3m2dp5fgy2slkajdx
  - &pc-installer age18jqsxdwhrwgsum8wefgt8jl2sj2277dzaj2yhwlj2vvfjqm9hazsmuvx7w
  - &rainbow-resort age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
  - &stinky-ssb age1gpdv8pq5f4efwkzchkxjyygr0g6tzzluqtepu6x0jzax5wnqeffq6ekyns
  - &thinkrac age1p400545a482fma40yfgytu40p6wr5a75v4f8yeudvgf7eh5erufqxhgynr
creation_rules:
  - path_regex: services/tailscale\.yaml$
    key_groups:
      - age:
          - *base
          - *instance-20221213-1915
          - *nas
          - *nixos-8gb-fsn1-1
          - *not522
          - *rainbow-resort
          - *stinky-ssb
          - *thinkrac
  - path_regex: services/restic\.yaml$
    key_groups:
      - age:
          - *base
          - *instance-20221213-1915
          - *nas
          - *nixos-8gb-fsn1-1
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *stinky-ssb
          - *thinkrac
  - path_regex: users/root/system\.yaml$
    key_groups:
      - age:
          - *base
          - *instance-20221213-1915
          - *nas
          - *nixos-8gb-fsn1-1
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *stinky-ssb
          - *thinkrac
  - path_regex: users/darkkirb/system\.yaml$
    key_groups:
      - age:
          - *base
          - *instance-20221213-1915
          - *nas
          - *nixos-8gb-fsn1-1
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *stinky-ssb
          - *thinkrac
  - path_regex: users/darkkirb/home-manager/keys.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: programs/desktop/music/listenbrainz.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: programs/ssh/shared-keys.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
          - *instance-20221213-1915
          - *nas
          - *nixos-8gb-fsn1-1
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *stinky-ssb
          - *thinkrac
  - path_regex: programs/desktop/pim/secrets.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: config/kde/krdp.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: services/desktop/gpg/privkey.yaml
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: services/postgresql/rainbow-resort.yaml
    key_groups:
      - age:
        - *base
        - *rainbow-resort
  - path_regex: services/postgresql/thinkrac.yaml
    key_groups:
      - age:
        - *base
        - *thinkrac
  - path_regex: services/postgresql/nas.yaml
    key_groups:
      - age:
        - *base
        - *nas
  - path_regex: services/postgresql/instance-20221213-1915.yaml
    key_groups:
      - age:
        - *base
        - *instance-20221213-1915
  - path_regex: services/postgresql/nixos-8gb-fsn1-1.yaml
    key_groups:
      - age:
        - *base
        - *nixos-8gb-fsn1-1
  - path_regex: services/acme/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nas
        - *nixos-8gb-fsn1-1
        - *instance-20221213-1915
        - *rainbow-resort
  - path_regex: services/atticd/secrets.yaml
    key_groups:
      - age:
        - *base
        - *instance-20221213-1915
  - path_regex: services/forgejo/secrets.yaml
    key_groups:
      - age:
        - *base
        - *instance-20221213-1915
  - path_regex: services/hydra/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nas
  - path_regex: services/prometheus/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nas
  - path_regex: services/yiffstash/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nas
  - path_regex: services/renovate/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nas
  - path_regex: services/chir-rs/secrets.yaml
    key_groups:
      - age:
        - *base
        - *instance-20221213-1915
        - *nas
        - *nixos-8gb-fsn1-1
        - *not522
        - *rainbow-resort
  - path_regex: services/named/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nixos-8gb-fsn1-1
  - path_regex: services/akkoma/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nixos-8gb-fsn1-1
  - path_regex: services/peertube/secrets.yaml
    key_groups:
      - age:
        - *base
        - *nixos-8gb-fsn1-1
  - path_regex: programs/desktop/development/rust/secrets.yaml
    key_groups:
      - age:
        - *base
        - *darkkirb
  - path_regex: services/matrix/secrets\.yaml$
    key_groups:
      - age:
          - *base
          - *nas
  - path_regex: services/kubernetes/secrets\.yaml$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
          - *nas
          - *instance-20221213-1915
          - *rainbow-resort
          - *base
  - path_regex: programs/desktop/development/secrets\.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb