keys:
  - &lotte 46C6A7E14BC7812E86C2700737FE303AAC2D06CD
  - &nixos-8gb-fsn1-1 age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
  - &nutty-noon age1wfftrnyngg7nxcwvt7m590fwx3w7p4kkrjn9uprjq0u3k3ym4s3qqzkmzm
  - &thinkrac age1e7tqq7ezjtwsunt6plvstevg32p97cmqpejpj20gmrkfe0l7gv9se08zf7
creation_rules:
  - path_regex: hosts/nixos-8gb-fsn1-1/secrets/.*$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
        pgp:
          - *lotte
  - path_regex: hosts/nutty-noon/secrets/.*$
    key_groups:
      - age:
          - *nutty-noon
        pgp:
          - *lotte
  - path_regex: hosts/thinkrac/secrets/.*$
    key_groups:
      - age:
          - *thinkrac
        pgp:
          - *lotte
  - path_regex: users/lotte/secrets/.*$
    key_groups:
      - pgp:
          - *lotte
  - path_regex: secrets/.*$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
          - *nutty-noon
          - *thinkrac
        pgp:
          - *lotte
