keys:
  - &lotte age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
  - &nixos-8gb-fsn1-1 age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
  - &thinkrac age1p400545a482fma40yfgytu40p6wr5a75v4f8yeudvgf7eh5erufqxhgynr
  - &nas age1c7y687sxh428wk34s8ws6kemu62mggafpt40rmanevgkuj5xa59q6f7tlc
  - &instance-20221213-1915 age1elra3uklw8rmwkevqms2l4tsd06d5utqda9d2w4qvqpz898uzuesugxkhc
  - &vf2 age1emv3kzvwgl36hgllrv7rlekqy3y3c6eztadl3lv09ks3z9vv6vdqw06yqa
  - &rainbow-resort age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
  - &devterm age1sqvl2cwvzeztuelpwppaestqufzeap8uf0vgy7t5mzr9rwc3dpxqhx8ly9
creation_rules:
  - path_regex: secrets/shared\.yaml$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
          - *thinkrac
          - *nas
          - *instance-20221213-1915
          - *vf2
          - *rainbow-resort
          - *lotte
          - *devterm
  - path_regex: secrets/nixos-8gb-fsn1-1\.yaml$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
          - *lotte
  - path_regex: secrets/thinkrac\.yaml$
    key_groups:
      - age:
          - *thinkrac
          - *lotte
  - path_regex: secrets/nixos\.yaml$
    key_groups:
      - age:
          - *lotte
  - path_regex: secrets/nas\.yaml$
    key_groups:
      - age:
          - *nas
          - *lotte
  - path_regex: secrets/desktop\.yaml$
    key_groups:
      - age:
          - *thinkrac
          - *rainbow-resort
          - *lotte
          - *devterm
  - path_regex: secrets/instance-20221213-1915\.yaml$
    key_groups:
      - age:
          - *instance-20221213-1915
          - *lotte
  - path_regex: secrets/vf2\.yaml$
    key_groups:
      - age:
          - *vf2
          - *lotte
  - path_regex: secrets/rainbow-resort\.yaml$
    key_groups:
      - age:
          - *rainbow-resort
          - *lotte
  - path_regex: secrets/devterm\.yaml$
    key_groups:
      - age:
          - *devterm
          - *lotte
  - path_regex: secrets/kubernetes\.yaml$
    key_groups:
      - age:
          - *nixos-8gb-fsn1-1
          - *nas
          - *instance-20221213-1915
          - *rainbow-resort
          - *lotte
