keys:
  - &base age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
  - &darkkirb age15g6tzvcmcp3ae4hwnn4pwewat6eq9unlhtjrlaka6rf94ej9dd5qqpgt7u
  - &not522 age1emv3kzvwgl36hgllrv7rlekqy3y3c6eztadl3lv09ks3z9vv6vdqw06yqa
  - &pc-installer age1eh2vd6cdy23qazwg0hzq95pn9e6p8yaqu4g6zyan8gzal4x5ed5qful8kg
  - &rainbow-resort age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
  - &thinkrac age1p400545a482fma40yfgytu40p6wr5a75v4f8yeudvgf7eh5erufqxhgynr
creation_rules:
  - path_regex: machine/not522/secrets\.yaml$
    key_groups:
      - age:
          - *base
          - *not522
  - path_regex: services/tailscale\.yaml$
    key_groups:
      - age:
          - *base
          - *not522
          - *rainbow-resort
          - *thinkrac
  - path_regex: services/restic\.yaml$
    key_groups:
      - age:
          - *base
          - *not522
          - *rainbow-resort
          - *thinkrac
  - path_regex: users/root/system\.yaml$
    key_groups:
      - age:
          - *base
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *thinkrac
  - path_regex: users/darkkirb/system\.yaml$
    key_groups:
      - age:
          - *base
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *thinkrac
  - path_regex: users/darkkirb/home-manager/keys.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: programs/ssh/shared-keys.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
          - *not522
          - *pc-installer
          - *rainbow-resort
          - *thinkrac
  - path_regex: programs/desktop/pim/secrets.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: config/kde/krdp.yaml$
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: services/desktop/gpg/privkey.yaml
    key_groups:
      - age:
          - *base
          - *darkkirb
  - path_regex: services/postgresql/rainbow-resort.yaml
    key_groups:
      - age:
        - *base
        - *rainbow-resort
  - path_regex: services/postgresql/thinkrac.yaml
    key_groups:
      - age:
        - *base
        - *thinkrac
  - path_regex: services/chir-rs/secrets.yaml
    key_groups:
      - age:
        - *base
        - *rainbow-resort
        - *not522
  - path_regex: programs/desktop/development/rust/secrets.yaml
    key_groups:
      - age:
        - *base
        - *darkkirb