schema = 3

[mod]
  [mod."github.com/kori/go-listenbrainz"]
    version = "v0.0.0-20230128070347-cd5ea1ae2e9f"
    hash = "sha256-Rmy5c5OS9AIzbhJZvMYHc7Re12l2aYpkGxk6DrVicIg="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
