services:
    chir-rs:
        paseto-secret-key: ENC[AES256_GCM,data:tTYBMA7LwmkKVyMERegZXnX5tL5lly0lL+nADBxDZN/cNQeQhZm+sT+VSg==,iv:OlFE1cpK3QQJ/DcuGHIjFc6+oLLLB9D4n+7sawiBD60=,tag:tmte7j9Fujc9NPoncEB1Ww==,type:str]
        access-key-id: ENC[AES256_GCM,data:o3TM4GMU94QesHvpaaSfIUb8txE=,iv:zmfDr+RNkuYoYUT8BNu1DZbj8D+MpnsyWLqUEdhrRp4=,tag:OCWNU6eIGYt76yMPisyFaA==,type:str]
        secret-access-key: ENC[AES256_GCM,data:kRxXzZpQje07Aoet5ga6RBnMlOLeF9dMMjrnzmvnHVOHK3FU04kAYQ==,iv:RNjJI9iBZRy+EM9EBPuVavVFEGOWy3+CyIId2Du8UYI=,tag:VgRyUGn77snLr4IbizrLrA==,type:str]
        database-url: ENC[AES256_GCM,data:WrbOtp/82my4ciEnxwU2Q331OwlW7Iy2TQbttlLWbyxRRm1uMmZ6YYn2vEsh71BSiGw/26JO+UuVjPNutGKwujUQWwWhNkJNcZ2f5ee1e2PzjrXKszeXblb5QJsvyx4R,iv:+eorzBca2pdQPbQhXCJOabCzjJw+XuU6j2tHp2fm1aU=,tag:7hy+v3RsKxGnrGy+H2F+7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4U1dSejljT1JzNjdQaFhH
            Q1o4WXRaWTRiUHBFOG80QXV3ekgwSm5KcGhBCmxXZlhyeE9JZDlkNnIwRGcrakd3
            V3BTcWZNcS84RWxoNm1DbURqcEZUWlEKLS0tIDFvV1hkOTlFeFJPTnJBQVIxZ0F4
            U0YrNVhEOHpBY1k5cWI5MU9rc3J1Y00KfDWRGhRIQnhkj+DoHxv9hDVfYZ+COnvB
            KPMi1LX9RVjKzBVhfhVheHpBcFb63InSlBFWbGDUvVz/j6WDUMAG+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c7y687sxh428wk34s8ws6kemu62mggafpt40rmanevgkuj5xa59q6f7tlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa0x6eklGSWF0WE9vZE9H
            NVBOdkl3cHpnUlFUbkRIY3BqTXUxN1NLMmpFCkxMR2s0YlQ2UGd6Si9qdUdyN3g4
            VUpBNU1NTysybktSZmVldmJXMXRLaUUKLS0tIDNDVVhBNTRTMjFHVjFyQjc2U0Qx
            clJ0cHNISXN3ZmUyc3V2ZW1VR01ieTQKv4zThHezYGDcf9vDql+Lynu6pE4v2y1X
            uB4Uc6Y7uYFY5QOigYJCXVzjN8e0oO/Wuhw1CXJKhMvueZnrGQ52/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1elra3uklw8rmwkevqms2l4tsd06d5utqda9d2w4qvqpz898uzuesugxkhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR3kyTDZVVGhMZnQ3bzFB
            Z1Zpd3Frc2k2YUNUVnNvYkdEb2FmY3RTbGljCmpaY0lYVkhtT3JMZjdkRjcxOG5L
            TTRVTzQvcXJYdUp4TVc3VlRvd0I5VFUKLS0tIC9zSHhWNWtzSXBxMUNGVEYxKzBU
            MkY1UGttNWp6bnI4RWlVaEcxSmNwaEkKBf8bHI1xFX3IVVeAXa1McmIEYGfFSJIN
            GSAZbAE45yIUhICPVUABbDeh1ktoWnemhaWIcjgrQYbcrvngBv1QwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMEc4MDVoa2J0VjdYVHZX
            UmNHVlFWMVUyTmtiSmVaL042QjBMUFBtZW5jCkc3YmFDMTJERjE5ZWoxeU5TZnF1
            SDdrQjBocU5LdkNXUFRxWlkrT3hNWlUKLS0tIG1rdkxabWtSSDUvYzYreFN1MHhq
            MFdZS1ZyYy9aUWFsaElxdElQSi9nRHcK0uMWpLyMJmoOd5w/s7/1lC8vfLuRnU9S
            DKSZr4FV8ujU8sA0UUDlaWcXvpgKIJDT49QiGjiSbyai+522MFKN0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sjh6SGhBSkFCVEJLbW5j
            YUZUNmJjUGwyUmVxdTlNL3BORUxlTlBpSkRnCmtWSFBCZEd3TE1QRG02L1ZURWxB
            b1Nsd3Q2aTB0WUF0QjNXR0ZrNmh6SU0KLS0tIG1rbUNYNm9RZTZpUFlIRk1YMnpI
            cEJHUzE3QjUyUUFQZWRYaGJ0c1NUSnMKWZnz5h//CEvfaaIqLfyDvVgX1iOaKtJS
            NMWPInLJGEWGetl1EiCLDnar9UNJBpqgzAt+TLNpe7QEC+RoceVXQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T10:18:58Z"
    mac: ENC[AES256_GCM,data:IKCioppowoNJYYnMkGikliH16L5q/+fRNqGjrE9HHIi+veo1hX2RjfvGWUvdYwlUHUa0MsuhlB1i36Y/rjZnVNI7jDWGojxFiqdPdreYvO7Scch0wnzQ+95FakvEobbfu8FKMcqL/OJFnKbsHMwqMC6hD4+DuBQl2UOz/caRXp8=,iv:JJLXqiPmvQogeT21nLg/etTWkhFAHotv1uL1C/8qp7U=,tag:s7Hl9ebm+YO16ocAvI/Ngw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
