schema = 3

[mod]
  [mod."github.com/ReneKroon/ttlcache/v2"]
    version = "v2.8.1"
    hash = "sha256-Qn8ARU4j35e8CUBa9OwW2xHM7ERKuorJP+9F/thjrt4="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.2.1"
    hash = "sha256-CKogmPe0pCcAdpztzPwr24rLTJZfq8QVZ9AUduwAcoA="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.3"
    hash = "sha256-qV3UPYKKBQDTzAUzzsTpfdbGhFnkmTO/r5ylPL1SyfA="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.5.0"
    hash = "sha256-2rhvuNZjeidDP+Og6Q0u4ROiaPrEOjoI5wCb17XRnOQ="
  [mod."github.com/getsentry/sentry-go"]
    version = "v0.24.1"
    hash = "sha256-R4QLkZwdUNgtGCqLcihcOY/F5GOOxthkAIK6jlgBjw4="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.17.0"
    hash = "sha256-EZTOzai8AoC4pTh3V4KcLbsGR+1b6U0WltkrZZA0YKg="
  [mod."github.com/jmoiron/sqlx"]
    version = "v1.3.3"
    hash = "sha256-bhpbvoyhgRME1EMQFBWR0vl/wWfuk4ZuKmELH9Sox/M="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/matrix-org/complement"]
    version = "v0.0.0-20231102222540-7efd8fce6d58"
    hash = "sha256-mdm+PRJ5pzMYdB8iRJXeuCSE1bcAONmhsOST8Mh3qfI="
  [mod."github.com/matrix-org/gomatrix"]
    version = "v0.0.0-20220926102614-ceba4d9f7530"
    hash = "sha256-q1wuafVA5IiyzSFatpIDl8+gLF98b2/m4Rusr9b83lU="
  [mod."github.com/matrix-org/gomatrixserverlib"]
    version = "v0.0.0-20230921171121-0466775328c7"
    hash = "sha256-jcnLQnmaJnII2RPOSTAgLeNzFns4VhciaFaWR1tVncU="
  [mod."github.com/matrix-org/util"]
    version = "v0.0.0-20221111132719-399730281e66"
    hash = "sha256-B9K93f1vgsLXwDgnZPDXIYeVlgaSlml/WxCEsyPl8c0="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.14.0"
    hash = "sha256-BoTCzWcRd3DJQmhY+6j48bguPxIrohOTM0M+yhxpdbs="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.13.0"
    hash = "sha256-5nC5FuGuAB71k6Dm4vBcmpPpBAKfvArO/yr7e9rfQfg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.37.0"
    hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.11.0"
    hash = "sha256-dfbKDyKmL+BNGVuvEZmw1CiGBiwqUADxJKkIi1Sbv1Y="
  [mod."github.com/rs/xid"]
    version = "v1.4.0"
    hash = "sha256-X7WH1cxWBof4m8ZWCnP0VYQdwzBti2eoa/sqm3BmLcg="
  [mod."github.com/rs/zerolog"]
    version = "v1.29.0"
    hash = "sha256-CVRSKk2O0nwAbu0fVY/JXpKaubJHhy9gtnSbEykPO3k="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/tidwall/gjson"]
    version = "v1.16.0"
    hash = "sha256-dpOHsSigxmZYBDTYO4d7jL4aTHUTPWDerogprK9/Iyw="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.1"
    hash = "sha256-S0uTDDGD8qr415Ut7QinyXljCp0TkL4zOIrlJ+9OMl8="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.5"
    hash = "sha256-OYGNolkmL7E1Qs2qrQ3IVpQp5gkcHNU/AB/z2O+Myps="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.44.0"
    hash = "sha256-V1fEoq1PpHB7KJ6ScfRNGFIrmMV03gOlyXCSCDQkLws="
  [mod."go.opentelemetry.io/contrib/propagators/jaeger"]
    version = "v1.18.0"
    hash = "sha256-T5Cv8Am1H5ypybI0RvFAa9fgpDjPls7Z5C0vARymMi4="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.18.0"
    hash = "sha256-gRETIwDXVMuxGZEoX2/SXkMvxNI3j7Qz0FCAYh2bKZ0="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.18.0"
    hash = "sha256-G29mBcyJbNK1JXy45lfISE/iUc9/LMlWCnwJLV8YCeU="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.18.0"
    hash = "sha256-ywp75OWF51CHG23Qe1P+h94w90T3dalaurW1Os+T1xc="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.18.0"
    hash = "sha256-rSQRem8ZO6N7LKgRikJ3Ffv6g1dMeXUh+cOwT/VLuPM="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.18.0"
    hash = "sha256-61OrnQD/LeXh+kkp/yE+HOiPdWaVHe5NnE8f4UbV8xs="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.18.0"
    hash = "sha256-wLwQZwb7dw6lbhBm2i1Pm8SpVW+XDmOKYYm/HE/b/w4="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.0.0"
    hash = "sha256-w2WbhXXshdm/ZmZkg5VpWwXFLjJRBBwSObyHGjJcELQ="
  [mod."golang.org/x/crypto"]
    version = "v0.14.0"
    hash = "sha256-UUSt3X/i34r1K0mU+Y5IzljX5HYy07JcHh39Pm1MU+o="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230905200255-921286631fa9"
    hash = "sha256-CyeVwjp12Wqh4ptqfi3KHCWPzOFhE8fSrP3sMjMXvec="
  [mod."golang.org/x/net"]
    version = "v0.17.0"
    hash = "sha256-qRawHWLSsJ06QNbLhUWPXGVSO1eaioeC9xZlUEWN8J8="
  [mod."golang.org/x/sync"]
    version = "v0.3.0"
    hash = "sha256-bCJKLvwExhYacH2ZrWlZ38lr1d6oNenNt2m1QqDCs0o="
  [mod."golang.org/x/sys"]
    version = "v0.13.0"
    hash = "sha256-/+RDZ0a0oEfJ0k304VqpJpdrl2ZXa3yFlOxy4mjW7w0="
  [mod."golang.org/x/text"]
    version = "v0.13.0"
    hash = "sha256-J34dbc8UNVIdRJUZP7jPt11oxuwG8VvrOOylxE7V3oA="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20230822172742-b8732ec3820d"
    hash = "sha256-qd9dJezVHNJZNMkywXapT1rsyD+lb25AU8aG8NJlhm4="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230822172742-b8732ec3820d"
    hash = "sha256-1kP7lqQ+fKtARDzTrRNob0owX4GsUnxzOwLyBZSmHOc="
  [mod."google.golang.org/grpc"]
    version = "v1.58.3"
    hash = "sha256-YxXO1UAc/+4E0bsSsGSiFNrY3yyR6AIml/1sVY2QJjQ="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."maunium.net/go/mautrix"]
    version = "v0.11.0"
    hash = "sha256-Mr0vqRMiKcf1OB/HVusFt/LizklScyGFs75mV6gU/bQ="
