etc:
    u2f_mappings: ENC[AES256_GCM,data:5pallRuDaC1vUtTrCwMFFqe2JGUCA/bkbd1L8pxc16jeJZs+pA+5ebC13YTI9IWc0cfHSOXVlp/BBwYwzIpqIRAyp1B6xnVqKeyQiInnkBF8uGZmPbEI8PQOXpM8De/2FUJsKMiFM48o1huvNKjwr1hv10O0vHqDr8LJdZFhgRUJdgqJ1mBXdvEnvLHGQ7r+lcoiTQ4bwpXBuESegFl26iZrASR+z7SImcBnlJLBsvSM4+aHrSt2JXttkZHC6QxnjLRpWjMCv6JXokJgmUgHsaWtQtrkEzW01Yd0CTAvzXtt5hfuSkMaILS+tDp3bx3lM/5TSYWHldcW+vTQc/SeEm3Bb0lpCo7dohIRHiXj+MG9/iDKGn7DYdwG6ev19NvQ2IS1dlFlX3Pulhb5ldBsRcBYn3tI5mRLbqh+JzxYI9GP0fBD8FdkHEXsthlkp6w3YGOFCqzgN9aRKFWL/CNhfMrDPaTJCdNCKe1sX46LSSiIVdRnCFRStbazuDNRv20y9AXZ5KLlXmVnmUY2+T/bXvUXtVswyMXJoA==,iv:UKbEngnGYOWVfxFGk3espX+xxL2TOXkYUagqfpb0Ntg=,tag:77z7lK1QM08Qlni1KsAlRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVnhvRXBWc0JiOTh3QjB1
            S205cnN0ZkZReHcrdm1YaUk3bnlOb1hBOURzCnR4am9YNjIwUUlVU0JXTEpMQTZl
            Z0xKY0tqNVBwMXk4SDJWTkZBZFJMSk0KLS0tIFRENlQ4aEUzcktxWWlEYlVLUDRP
            ZUtvQ1NYTlhwS1NhYXpXbFV4VlB6ajQKN7jZVQF5EH7q6gaEx+BJwgvaV99cwC9p
            xRLxsU3xp5jtaSlqil2fQHfOCHIxdfL8hSqZ1ILVLch0H+tAzhmSbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrejluRWlENzBWSkdlNVVX
            TTEyd1Y3ZlNBcXk1bngxR0FBVTNSeWRsc0Q0CjVZT0x4Ymx2ekhTSndseUlJYnhs
            dSt2Qm9IZWFmbndhVVV0L2ZLaEYvWkkKLS0tIEdMZUZZVGpTdjlmWHk4TFA2ZjZM
            eVV5bThMbTlpVktqYWtITUxKMkJRVWMKXbN7F+FrqjChBIkRv0UO4hK2EIdo91sh
            97KnHq9pCFlmF9x+MPvj8vS6xtin2+oglLh9Sp3yUZ+pVBwoYZuwOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p400545a482fma40yfgytu40p6wr5a75v4f8yeudvgf7eh5erufqxhgynr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTCtFMDFYaUhtTDllZ1Za
            TTlaaW9WZzBtRUc0ZS9kOEZVT3ZBaTBSbmtFCmpaVk1NTFppUE9DUzA5UTNBQU5O
            cWhzQStxSG9kMDdBUEhkL2lOaFoyaXcKLS0tIHRNWkFvREdkZU8zZ3JOZXdMOGc2
            d0gxWHpZaEpOa2NoT05EN2JjV092b28K0yrkttUqrHKkQZPPfIi6aFK3cXrqoogn
            eA/OXTqMsrzLKLGytoQhVlE8tuolmJpZsESsHefY6qbTC2oSPi3phQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nvgqlpqe026czej7erz5a7ptulzzhh7tht3gjzy5s3m2dp5fgy2slkajdx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a283djhqbXVtT01OUjRq
            RXI4WVU5L1E5RXEzc2NHdjBVMWpjemFWN3pBCnpmU0QrYlVTUm1uUDNEclZYMFh6
            dXYxbDcwUnR1TEkySHlVeTU1UnRscE0KLS0tIGFNOWxqN0pvNEx5b2c2eXJzUFdK
            ZW9XbzZlVUErdyt2ZUFpNURYRlJ5ZlEKkTN6IcMHQ36ueii2WSgquT9bvU2YCABu
            TUGp6ThsCZ+UENhznbf7M57jby3KHAckvbAGL1/O470o5sCyifPohQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jqsxdwhrwgsum8wefgt8jl2sj2277dzaj2yhwlj2vvfjqm9hazsmuvx7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYTArZ3VhY1ZtWEIyUHA3
            V0VESWRGUW92VzJJcWJJZ2hJczgxdHhsd0dJCkZwb2FETzA3VHhkMWtVTHJ3VWZq
            VGtsTklXdlk1eDNqZ1VoNm80S2FJcTgKLS0tIDA0TTJGOVZzcU5vV3F3c0xjZmll
            OUh3Vjk3UE9CSlBCZXAwb0JvNHhvYm8KpkzAUCGhYBSzUdzSYabwcfiGhg1XKydB
            vVPYIUfq9l0BLZLQ/Dllx8gxRbr0+zIlVulvhd2kjNX+fP1gJ5JZmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T17:06:02Z"
    mac: ENC[AES256_GCM,data:ReybKzTcOaEjkjBAxWpjk6nZNQEM5mPVFeWYEf8CkFZ01gz1B28czFJYmDhqhQ98U6fpEErEOQp5BXLUTLJBITniaHiWU5tKJV/Ans7xvhcEPCxxal9rRcghcl3OST3A+NxeSlRDr4yOsQthqHQIlPkOjXNDfPU/rEJ1qtHU8yc=,iv:QXuMSEGwWJopnLMMI1/X7KOzhcG129KQfATM+rj8VPw=,tag:3kYNAe1aDpyhv//z/XVB1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
