etc:
    u2f_mappings: ENC[AES256_GCM,data:5pallRuDaC1vUtTrCwMFFqe2JGUCA/bkbd1L8pxc16jeJZs+pA+5ebC13YTI9IWc0cfHSOXVlp/BBwYwzIpqIRAyp1B6xnVqKeyQiInnkBF8uGZmPbEI8PQOXpM8De/2FUJsKMiFM48o1huvNKjwr1hv10O0vHqDr8LJdZFhgRUJdgqJ1mBXdvEnvLHGQ7r+lcoiTQ4bwpXBuESegFl26iZrASR+z7SImcBnlJLBsvSM4+aHrSt2JXttkZHC6QxnjLRpWjMCv6JXokJgmUgHsaWtQtrkEzW01Yd0CTAvzXtt5hfuSkMaILS+tDp3bx3lM/5TSYWHldcW+vTQc/SeEm3Bb0lpCo7dohIRHiXj+MG9/iDKGn7DYdwG6ev19NvQ2IS1dlFlX3Pulhb5ldBsRcBYn3tI5mRLbqh+JzxYI9GP0fBD8FdkHEXsthlkp6w3YGOFCqzgN9aRKFWL/CNhfMrDPaTJCdNCKe1sX46LSSiIVdRnCFRStbazuDNRv20y9AXZ5KLlXmVnmUY2+T/bXvUXtVswyMXJoA==,iv:UKbEngnGYOWVfxFGk3espX+xxL2TOXkYUagqfpb0Ntg=,tag:77z7lK1QM08Qlni1KsAlRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ0ExZ1hTN3ZncE8xaUFG
            bUp1QTgzZ3I5TU5USlROZVBNcmhWOEN6bG1nCnRXWWY0KzVTNjdENEQ5dUlDVEU2
            RVNvUit1OWlQYVNPVmh2a0NObTIza2sKLS0tIE1JOHVvWHloOURyd1BUVHVKcTI1
            cGVBT3R6bjdvYlNSWkdieWVBRGhRc0kK/nQcygSBsPFG1DRxBiAQwYq7IstOxEaz
            /U0zefWPOC859cIcZLJRtOD8PI7brlyFmv/WXBXB2lXQOGymsntTGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV3JSTDVyRThpUGdlWDlz
            Y3ZTV1hEODJIaGFwTDhTUWFKYUNlQTllaWg0ClVQWENobm9IcytNZm4zUUpmcXVy
            Q2pKR1VYQWxHUDBxVUk3aEhCV3BOdzQKLS0tIGlZVTRlZStXZndGYzZCS1Jzc083
            R2VoSDAwdlJJalk2cUkrNU5VZkV3QXMKPOQQ7vVv3jD6uX3ma0F9JMM8yLK8PgU7
            4wmGGPWJR4wjvVKSAD6XGdN8v67VrI0uqpRRiifZgga9iTRKoUzNRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p400545a482fma40yfgytu40p6wr5a75v4f8yeudvgf7eh5erufqxhgynr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZnlrSEt3aTE3RmZTVWc0
            L1liZnZZVXlTUnhGQm1Nc1BiQWFCUmVjRkJFCmVJV21iVWRGSVFrSk5hSTd3Z3Vt
            Z3lhZDE1UmV5SUlNamhqcWxuazF4V0kKLS0tIDBkVmZmcmVUanBqOEF6SWJoTzUz
            eXVqYVZYcGJTVGU0VGNHTm92WW0weDgKvosC/ViptI+vA/+WrGyEv8QnknCFGLIl
            FdIbTHUT1RpDTEtd1V2RE1Ee9dC1JaqGqOqSNAEDQtrT9aahMuyZTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nvgqlpqe026czej7erz5a7ptulzzhh7tht3gjzy5s3m2dp5fgy2slkajdx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU0x2b3p5bTVrVHNJR1d5
            dnFmdnd1S1dMK1dZU1lNNEhvNllBdVJCTVFRCjBVY3FpUUltaE9zZWQ5bll2RlFH
            aXg5V0ZTYTBvTXpUMFNFajMvdjkvbVkKLS0tIDZhaElkM3lQYUM5M0pZcmcyWDZK
            RlloVGdWdm4vcXVTZ3Y0Nkl3V3JITVUKf1Ho045tiIs5con6LAdInQe8pyUwrwSo
            4dlEuJMToALXdaYYNhAbf6U3AWrluM4RqBF/cmnuV7VZxntT1Ni0lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jqsxdwhrwgsum8wefgt8jl2sj2277dzaj2yhwlj2vvfjqm9hazsmuvx7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT1YySmxGNlNOZldKL3Zj
            TkJKQkd5ZTlXUnlyOTdLWmxwVlNEN1ZiZUFrCmVHUlUxei9Ya1E4NXFGRVVzRHYx
            akpYeVNOWmRlbDJ6WWFJMUtybkVuSnMKLS0tIFRST3U0UGZwYmZpUE5MZWtaY0s5
            aEJ5TmR3M05kNzNiamV6WngyZTl6U3cKbhlHrKrQYq2IelNd6v8Syz8TdxHUDUyd
            OoqisXmEMTjg++VGVq3OTGmgMRF717N7ro1RevvoGNgmvnn9Uocn1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10mukztj2s6s0r57dg30694gry4k4cxslhrey9wwx9jz5ehn7y9nslvy3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Unc2cDBBN0lQcEdGZ3pR
            Umlva2p5R0RVeGFHdy9QTEU2N25ab2xnTno0Cko3YWhxa2NocHFoNGpVcmhvNmYz
            cnZQVWRpMXZxT3VFYVRhenJQR2dPMHMKLS0tIEh3QitBL0RWQ29aV1RNcFd2Tk1r
            eWFqQ0w4VW1NYThaSnBBUS9GbFlyM3MKhDvPsfJna9VTrxDRuqnF/AAm0+dwOGKh
            w5yaJnwtoSgDUeIjwMuQfEsHrm+GS5pnymcswyc3YpfvoMg9P7gxkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T17:06:02Z"
    mac: ENC[AES256_GCM,data:ReybKzTcOaEjkjBAxWpjk6nZNQEM5mPVFeWYEf8CkFZ01gz1B28czFJYmDhqhQ98U6fpEErEOQp5BXLUTLJBITniaHiWU5tKJV/Ans7xvhcEPCxxal9rRcghcl3OST3A+NxeSlRDr4yOsQthqHQIlPkOjXNDfPU/rEJ1qtHU8yc=,iv:QXuMSEGwWJopnLMMI1/X7KOzhcG129KQfATM+rj8VPw=,tag:3kYNAe1aDpyhv//z/XVB1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
