schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v1.4.1-0.20240526193622-a339e1f7089c"
    hash = "sha256-ixpMR6uwjREWWfY9rStfd5AB7UGkE3EqlR7JocUK+JE="
  [mod."github.com/a-h/parse"]
    version = "v0.0.0-20250122154542-74294addb73e"
    hash = "sha256-xKu8VwLQSdqR2oeUwah0w5P2ISP2JtVELTfX5ESMWfE="
  [mod."github.com/a-h/templ"]
    version = "v0.3.857"
    hash = "sha256-OI7Y4AP2XAV1XyNqUQapINWkSD9LCWgNaNYHQZBVaro="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.1.0"
    hash = "sha256-njLViV4v++ZdgOWGWzlvkefuFvA/nkugl3Ta/h1nu/0="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/cli/browser"]
    version = "v1.3.0"
    hash = "sha256-06hcvQeOEm31clxkTuZ8ts8ZtdNKY575EsM1osRVpLg="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/deckarep/golang-set/v2"]
    version = "v2.6.0"
    hash = "sha256-ni1XK75Q8iBBmxgoyZTedP4RmrUPzFC4978xB4HKdfs="
  [mod."github.com/facebookgo/ensure"]
    version = "v0.0.0-20160127193407-b4ab57deab51"
    hash = "sha256-jdCvva9KDH6KTTAtW0fBNw67xd0DhxLQbxU8PdhWLKY="
  [mod."github.com/facebookgo/flagenv"]
    version = "v0.0.0-20160425205200-fcd59fca7456"
    hash = "sha256-Dx2QQ7FngN64CDL1I3jQG4JOzzCKnt6MsbnVRzzh7jA="
  [mod."github.com/facebookgo/stack"]
    version = "v0.0.0-20160209184415-751773369052"
    hash = "sha256-o6JL8oyrSBcgbdkvjUi4PT5OnfwgyXgbPQDA82sB2R8="
  [mod."github.com/facebookgo/subset"]
    version = "v0.0.0-20150612182917-8dac2c3c4870"
    hash = "sha256-Ub0cBFwF6MBzTZ7fpqxrC375arBv+au5I/LLzksVzE8="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.7.0"
    hash = "sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.4"
    hash = "sha256-RrLHCu9l6k0XVobdZQJ9Sx/VTQcWjrdLR5BEG7yXTEQ="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.2.2"
    hash = "sha256-C0MhDguxWR6dQUrNVQ5xaFUReSV6CVEBAijG3b4wnX4="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/natefinch/atomic"]
    version = "v1.0.1"
    hash = "sha256-fbOVHCwRNI8PFjC4o0YXpKZO0JU2aWTfH5c7WXXKMHg="
  [mod."github.com/playwright-community/playwright-go"]
    version = "v0.5101.0"
    hash = "sha256-nkfvulYgDnbYlHF7kXtD7526V4vtdjoO7OS9t2DLuBs="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.22.0"
    hash = "sha256-OJ/9rlWG1DIPQJAZUTzjykkX0o+f+4IKLvW8YityaMQ="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.62.0"
    hash = "sha256-UFccvzMJaBrUpnqVgZgohRcgk5SKMi/UJnXNtazCnx8="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/sebest/xff"]
    version = "v0.0.0-20210106013422-671bd2870b3a"
    hash = "sha256-t7Gdp7S71Koej5Njg3jOo5vwyj02tJCbJjrq/vZGOho="
  [mod."github.com/yl2chen/cidranger"]
    version = "v1.0.2"
    hash = "sha256-rPZApwakcZ1D3lmZnFds79+TFr9IlYkovTA7o52N9h0="
  [mod."golang.org/x/exp/typeparams"]
    version = "v0.0.0-20231108232855-2478ac86f678"
    hash = "sha256-0uQMDDiRS2ZMGdS4k7/+JgP7SHC0p+sA9bnywR+sTuU="
  [mod."golang.org/x/mod"]
    version = "v0.24.0"
    hash = "sha256-Lrl4RzOO0J/S5E+AQ7Y6yh8B9yygvZ2W0fsKEtBSYNU="
  [mod."golang.org/x/net"]
    version = "v0.39.0"
    hash = "sha256-IP29+yGphWKUT7wHTyzqA2rnRT4AJ7oWcT6NKLzkWcM="
  [mod."golang.org/x/sync"]
    version = "v0.12.0"
    hash = "sha256-lPIbI6aXx+iKtFjPaXKNLEnuNfhHCVl7EQiE7alUvlM="
  [mod."golang.org/x/sys"]
    version = "v0.32.0"
    hash = "sha256-c9RRnyKQy9Kl8hpbtcgkm1O5H7gOdk9Rv925F8fZS6E="
  [mod."golang.org/x/tools"]
    version = "v0.31.0"
    hash = "sha256-NXyG75xnCUX4EpW0Jmm1qpPbwhaiMxgJqvCU1X5oGyk="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.5"
    hash = "sha256-isupBiQUrKPEFzK94k5cgzM3Ab5fMXp352/zcsXV1JU="
  [mod."honnef.co/go/tools"]
    version = "v0.6.1"
    hash = "sha256-cunOp0OURbxRV4vQrQtzRX5Jbe6eVpuENAefEyubxqo="
