k3s:
    token: ENC[AES256_GCM,data:Tl35Wlw5Ypp3UnI4+uHKUuvuGA2X0cE544KRa7943+k=,iv:aOmi6fkumaVGCgzasZr18fO6xQftf7a8yn9Aw5PGkac=,tag:gfRrrqZv7IqOO/zlxKscQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1273ps5thcy70ckdt0270s2nysqgu48t38pq3wq975v3y7mf4eavsw38wsl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcXJMNkdVaXpRZHRhc1V2
            M1lmUHh3TzhPMmw5YmF1alpNdmJoMWdwVnkwClUzYWZuYitkR0R1MC9hdEs4Ky96
            QW02NEtteTVxNEZBVElFUGpmdWhVYWsKLS0tIG1najN4ZFNrNkVzS3JvR3JhYjhX
            U3hrZXZuRGJiMTROaHBTNldkK28rMTgK/NkN09eXL74/Rj+UGe6+svXdnRSpqXE+
            zYf+IiVo80mQGNBrirDehep/bP+AGQSNXP9dSBHCU19i7EYr+ZKryw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c7y687sxh428wk34s8ws6kemu62mggafpt40rmanevgkuj5xa59q6f7tlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVDk1M1ptU3BLTGg1RGp0
            RWlBcjA2RjJjbGFMb2RiMVJidUtWTnVwdVF3CnZKV0lzMTVFN1EydzlxM1R2TEM3
            SEI5UkFKdVBpUldJSHBKSWJIQ0l0cHcKLS0tIEgwdzlqd3BwUS9GbTQ0SlhKa2VI
            MURHZzZMY2FxYmJ6a1pRS2J5RjEyZlkKRZWoCzposZNfSKJlEnu1Fwzv7G9cPjug
            jq2UUWxBrYc6TJYbZl+zLOKomtyW5wab+wp39sJjZsJLXGZvRctj6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1elra3uklw8rmwkevqms2l4tsd06d5utqda9d2w4qvqpz898uzuesugxkhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR05sUVB6dWhrT0orN0wv
            Z3Evcld2em85VThYK2t6ZXpKN0V6VnZEM0NvCitiTTFpQnk3TmNCa3F5dXpMVXFU
            em8yWGp4b0EyUGtWL1BQbEVqR2ZUZVkKLS0tIGErbVA0OWlQZnJIMGplNVRteEpK
            WDRCMHZtdy9PYVlmL2lhSTlNSHJ4encKzr3B0P0Wq0BSijoBPQMwsDGSd+HCukuj
            OO3/NfBV5CPgYMRuucTTKVVcTqerdn0sCtPKsexA9xMWnitjz3jGRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19vzypddhexvvsf8xylstxc9znnkd8rxmamhjlt7elvz4j3zaf5tqqura6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVBrV1d2bm15WFI5ZWhv
            VnFpUEpiaUUwT083ZnhEaElQdzJYOGVUeUJrCmYybURUUG1xQmI1RDVFOTIwWkQ2
            dzQ4RHg4Z2pEbE8vV1hoVnlNYVEwWU0KLS0tIDhsVzlwbU9PMG5HQm9rZkpWeXJv
            WXZDNmZNcTJkaFpCcFlqTlE5c05mZDQKagVuhOjSF19gWlI5wJ2SCyhVe5Svpz2N
            IPLgDS0EQR4X6cQ+5dtMbtMR53uILGmsvmnSKZQEnc14ySOqfdzKQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tltjgexkp5fz3rum4j0k66ty5q4u8ptvkgkepumd20zal24g2qfs5xgw76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMVFpWEIyTS9tQTZaa3Fm
            eVRYbk84VWI1aTNhUytPOGJmQ2p4ZUhhUXd3CnJKb1dScUdIcktwdlhDVmUyTTFC
            RDdEYlhiQjdPUmVvWHg0dUROZnBRaUkKLS0tIEREcll0bi9sc3pKdzdMNisrT1BU
            ZlZxbDVIQjNyeW80N1I3UW1oVVBmQWMKCzBkGcrW6TbIn3kT5ycdzShP9cSTJ0y+
            zesQi9IKjc1YRdIh46RuciqsEJ9bLTqsFdoTLdIuF4PjxTQT9vfv3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T11:25:47Z"
    mac: ENC[AES256_GCM,data:WRSOBaESB6Hpg+zfwAqCef1d/QapWbe0gcgICVzKz+gRURJIBSJ9q95PbmeuKreN8Ke8peGH4VAxzoORcq4pO0E6l2xsdPHLz+PhZaul+mnTMRJckW45RMTN/7+jK8Mhe3ONw8qxlARptTsQ/tm65+7599YLQXcGgfO5rqRmMmQ=,iv:UGSy6sMKMaW4ihZcZZjrN28VdH8Z8rSUmXaFO0c1bWw=,tag:nx4tVfMcMpMe65mgxSpdkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
