pipeline:
  deploy-acl:
    image: golang:1.18.4-alpine3.16
    commands:
      - go install tailscale.com/cmd/gitops-pusher@gitops-1.30.0
      - /go/bin/gitops-pusher --policy-file=config/tailscale.hujson apply
    when:
      event: push
      branch: main
    secrets:
      - ts_api_key
      - ts_tailnet
  test-acl:
    image: golang:1.18.4-alpine3.16
    commands:
      - go install tailscale.com/cmd/gitops-pusher@gitops-1.30.0
      - /go/bin/gitops-pusher --policy-file=config/tailscale.hujson test
    when:
      event: pull_request
    secrets:
      - ts_api_key
      - ts_tailnet
