name: Build installer iso
on:
  schedule:
    - cron: "45 14 * * 1"
  workflow_dispatch: {}
jobs:
  build-install-iso:
    name: Build installer iso
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: nixos-config/nixos-config/installer.x86_64-linux
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            substituters = https://f000.backblazeb2.com/file/cache-chir-rs/ https://cache.nixos.org/
            trusted-public-keys = nixcache:8KKuGz95Pk4UJ5W/Ni+pN+v+LDTkMMFV4yrGmAYgkDg= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs=
      - run: nix build '.#nixcosConfigurations.installer.config.system.build.isoImage'
      - run: wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc
      - run: ./mc alias set b2 https://s3.us-west-000.backblazeb2.com ${{ secrets.B2_ACCESS_KEY_ID }} ${{ secrets.B2_SECRET_ACCESS_KEY }}
      - run: ./mc cp result b2/cache-chir-rs/installer.iso
