name: build
on:
  pull_request:
    branches:
      - main
jobs:
  base-server-x86_64:
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: server-x86_64.x86_64-linux
    secrets: inherit
  base-server-aarch64:
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: server-aarch64.aarch64-linux
    secrets: inherit
  base-desktop-x86_64:
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: desktop-x86_64.x86_64-linux
    secrets: inherit
  nas:
    needs: base-server-x86_64
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: nas.x86_64-linux
    secrets: inherit
  nixos-8gb-fsn1-1:
    needs: base-server-x86_64
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: nixos-8gb-fsn1-1.x86_64-linux
    secrets: inherit
  nutty-noon:
    needs: base-desktop-x86_64
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: nutty-noon.x86_64-linux
    secrets: inherit
  thinkrac:
    needs: base-desktop-x86_64
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: thinkrac.x86_64-linux
    secrets: inherit
  instance-20221213-1915:
    needs: base-server-aarch64
    uses: ./.github/workflows/build-one.yml
    with:
      hostname: instance-20221213-1915.aarch64-linux
    secrets: inherit
