name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: Deploy to staging
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: git-checkout
        uses: actions/checkout@v2
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          force: true
