name: Deploy to staging
on:
  workflow_dispatch:
    inputs:
      job_name:
        description: "Job name that has completed"
        required: true
        type: string
jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git tag -f ${{ inputs.job_name }}
      - run: git push --tags
