name: Deploy to staging
on:
  status

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        if: github.event.state == 'success'
      - name: Push
        uses: ad-m/github-push-action@master
        if: github.event.state == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          force: true
