name: Build pull request
on: pull_request

jobs:
  build_pr:
    name: Build Pull
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - nixosConfigurations.nixos-8gb-fsn1-1.config.system.build.toplevel
          - nixosConfigurations.nutty-noon.config.system.build.toplevel
          - nixosConfigurations.thinkrac.config.system.build.toplevel
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            substituters = https://f000.backblazeb2.com/file/cache-chir-rs/ https://cache.nixos.org/
            trusted-public-keys = nixcache:8KKuGz95Pk4UJ5W/Ni+pN+v+LDTkMMFV4yrGmAYgkDg= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs=
      - run: nix build --no-link '.#${{ matrix.target }}'
