name: update-riscv
on:
  push:
    branches:
      - main
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Create update pull request
        run: |
          curl -X 'POST' \
            'https://git.chir.rs/api/v1/repos/darkkirb/nixos-config/pulls' \
            -H 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{
            "base": "main-riscv",
            "body": "Keeping main-riscv up to date",
            "head": "main",
            "title": "Update RISC-V config"
          }'
