name: update-riscv
on:
  push:
    branches:
      - main
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create update pull request
        uses: LucasRuy/sync-branch-action@v1.1.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SOURCE_BRANCH: 'main'
          DESTINATION_BRANCH: 'main-riscv'
