name: Update flake
on:
  schedule:
    - cron: "35 * * * *"
  workflow_dispatch: {}
jobs:
  update-flake:
    name: Update flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
      - uses: cachix/install-nix-action@v12
      - run: nix flake update --extra-experimental-features "nix-command flakes"
      - run: git config user.email autoupdate@chir.rs
      - run: git config user.name "Autoupdater"
      - run: git commit -am "Automatic update" || true
      - run: git push
