name: Update flake
on:
  schedule:
    - cron: "35 * * * *"
  workflow_dispatch: {}
jobs:
  update-flake:
    name: Update flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations
            substituters = https://f000.backblazeb2.com/file/cache-chir-rs/ https://cache.nixos.org/
            trusted-public-keys = nixcache:8KKuGz95Pk4UJ5W/Ni+pN+v+LDTkMMFV4yrGmAYgkDg= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs=
      - run: nix flake update
      - run: git config user.email autoupdate@chir.rs
      - run: git config user.name "Autoupdater"
      - run: git commit -am "Automatic update" || true
      - run: git push
